http {
    geo $rate_limit {
        default "10r/m"
    }

    # create zone
    # 10mb for that zone
    # 10rps
    limit_req_zone $binary_remote_addr zone=insurance_client_zone:10m rate=$rate_limit;

    # Настройка upstream для балансировки нагрузки
    upstream backend_servers {
        server backend1.example.com;
        server backend2.example.com;
        server backend3.example.com;
    }

    server {
        listen 80;

        location / {
            # 2-stage limit for 11-16th requests
            # limit_req zone=insurance_client_zone burst=6 delay=2;
            
            # above (limit + 2-stage limit) requests would get this error
            limit_req_status 429;
            
            proxy_pass http://backend_servers;
            
            # insurance company would get response with that header info
            # ??? not sure how to extract number from $rate_limit properly
            add_header X-RateLimit-Limit "10";
            add_header X-RateLimit-Remaining "$remaining";
            add_header X-RateLimit-Reset "$limit";
        }
    }
}